-- create "mails" table
CREATE TABLE "mails" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "to" character varying NOT NULL,
  "from" character varying NOT NULL,
  "raw" bytea NOT NULL,
  "incoming_mail_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- create "outbox" table
CREATE TABLE "outbox" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "topic" text NOT NULL,
  "data" bytea NOT NULL,
  "inserted_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "outbox_topic_id" to table: "outbox"
CREATE INDEX "outbox_topic_id" ON "outbox" ("topic", "id");
