// Code generated by ent, DO NOT EDIT.

package mail

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mail type in the database.
	Label = "mail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTo holds the string denoting the to field in the database.
	FieldTo = "to"
	// FieldFrom holds the string denoting the from field in the database.
	FieldFrom = "from"
	// FieldRaw holds the string denoting the raw field in the database.
	FieldRaw = "raw"
	// FieldIncomingMailID holds the string denoting the incoming_mail_id field in the database.
	FieldIncomingMailID = "incoming_mail_id"
	// Table holds the table name of the mail in the database.
	Table = "mails"
)

// Columns holds all SQL columns for mail fields.
var Columns = []string{
	FieldID,
	FieldTo,
	FieldFrom,
	FieldRaw,
	FieldIncomingMailID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Mail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTo orders the results by the to field.
func ByTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTo, opts...).ToFunc()
}

// ByFrom orders the results by the from field.
func ByFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrom, opts...).ToFunc()
}

// ByIncomingMailID orders the results by the incoming_mail_id field.
func ByIncomingMailID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncomingMailID, opts...).ToFunc()
}
