// Code generated by ent, DO NOT EDIT.

package incomingmail

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the incomingmail type in the database.
	Label = "incoming_mail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTo holds the string denoting the to field in the database.
	FieldTo = "to"
	// FieldFrom holds the string denoting the from field in the database.
	FieldFrom = "from"
	// FieldRaw holds the string denoting the raw field in the database.
	FieldRaw = "raw"
	// Table holds the table name of the incomingmail in the database.
	Table = "incoming_mails"
)

// Columns holds all SQL columns for incomingmail fields.
var Columns = []string{
	FieldID,
	FieldTo,
	FieldFrom,
	FieldRaw,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the IncomingMail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTo orders the results by the to field.
func ByTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTo, opts...).ToFunc()
}

// ByFrom orders the results by the from field.
func ByFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrom, opts...).ToFunc()
}
