// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IncomingMail is the predicate function for incomingmail builders.
type IncomingMail func(*sql.Selector)

// Outbox is the predicate function for outbox builders.
type Outbox func(*sql.Selector)
