// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"encore.app/processor/ent/mail"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MailCreate is the builder for creating a Mail entity.
type MailCreate struct {
	config
	mutation *MailMutation
	hooks    []Hook
}

// SetTo sets the "to" field.
func (mc *MailCreate) SetTo(s string) *MailCreate {
	mc.mutation.SetTo(s)
	return mc
}

// SetFrom sets the "from" field.
func (mc *MailCreate) SetFrom(s string) *MailCreate {
	mc.mutation.SetFrom(s)
	return mc
}

// SetRaw sets the "raw" field.
func (mc *MailCreate) SetRaw(b []byte) *MailCreate {
	mc.mutation.SetRaw(b)
	return mc
}

// SetIncomingMailID sets the "incoming_mail_id" field.
func (mc *MailCreate) SetIncomingMailID(i int) *MailCreate {
	mc.mutation.SetIncomingMailID(i)
	return mc
}

// Mutation returns the MailMutation object of the builder.
func (mc *MailCreate) Mutation() *MailMutation {
	return mc.mutation
}

// Save creates the Mail in the database.
func (mc *MailCreate) Save(ctx context.Context) (*Mail, error) {
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MailCreate) SaveX(ctx context.Context) *Mail {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MailCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MailCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MailCreate) check() error {
	if _, ok := mc.mutation.To(); !ok {
		return &ValidationError{Name: "to", err: errors.New(`ent: missing required field "Mail.to"`)}
	}
	if _, ok := mc.mutation.From(); !ok {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required field "Mail.from"`)}
	}
	if _, ok := mc.mutation.Raw(); !ok {
		return &ValidationError{Name: "raw", err: errors.New(`ent: missing required field "Mail.raw"`)}
	}
	if _, ok := mc.mutation.IncomingMailID(); !ok {
		return &ValidationError{Name: "incoming_mail_id", err: errors.New(`ent: missing required field "Mail.incoming_mail_id"`)}
	}
	return nil
}

func (mc *MailCreate) sqlSave(ctx context.Context) (*Mail, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MailCreate) createSpec() (*Mail, *sqlgraph.CreateSpec) {
	var (
		_node = &Mail{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(mail.Table, sqlgraph.NewFieldSpec(mail.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.To(); ok {
		_spec.SetField(mail.FieldTo, field.TypeString, value)
		_node.To = value
	}
	if value, ok := mc.mutation.From(); ok {
		_spec.SetField(mail.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := mc.mutation.Raw(); ok {
		_spec.SetField(mail.FieldRaw, field.TypeBytes, value)
		_node.Raw = value
	}
	if value, ok := mc.mutation.IncomingMailID(); ok {
		_spec.SetField(mail.FieldIncomingMailID, field.TypeInt, value)
		_node.IncomingMailID = value
	}
	return _node, _spec
}

// MailCreateBulk is the builder for creating many Mail entities in bulk.
type MailCreateBulk struct {
	config
	err      error
	builders []*MailCreate
}

// Save creates the Mail entities in the database.
func (mcb *MailCreateBulk) Save(ctx context.Context) ([]*Mail, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Mail, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MailCreateBulk) SaveX(ctx context.Context) []*Mail {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MailCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MailCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
