// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/processor/ent/outbox"
	"encore.app/processor/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OutboxUpdate is the builder for updating Outbox entities.
type OutboxUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxMutation
}

// Where appends a list predicates to the OutboxUpdate builder.
func (ou *OutboxUpdate) Where(ps ...predicate.Outbox) *OutboxUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetTopic sets the "topic" field.
func (ou *OutboxUpdate) SetTopic(s string) *OutboxUpdate {
	ou.mutation.SetTopic(s)
	return ou
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (ou *OutboxUpdate) SetNillableTopic(s *string) *OutboxUpdate {
	if s != nil {
		ou.SetTopic(*s)
	}
	return ou
}

// SetData sets the "data" field.
func (ou *OutboxUpdate) SetData(b []byte) *OutboxUpdate {
	ou.mutation.SetData(b)
	return ou
}

// SetInsertedAt sets the "inserted_at" field.
func (ou *OutboxUpdate) SetInsertedAt(t time.Time) *OutboxUpdate {
	ou.mutation.SetInsertedAt(t)
	return ou
}

// SetNillableInsertedAt sets the "inserted_at" field if the given value is not nil.
func (ou *OutboxUpdate) SetNillableInsertedAt(t *time.Time) *OutboxUpdate {
	if t != nil {
		ou.SetInsertedAt(*t)
	}
	return ou
}

// Mutation returns the OutboxMutation object of the builder.
func (ou *OutboxUpdate) Mutation() *OutboxMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OutboxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OutboxUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OutboxUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ou *OutboxUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(outbox.Table, outbox.Columns, sqlgraph.NewFieldSpec(outbox.FieldID, field.TypeInt64))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Topic(); ok {
		_spec.SetField(outbox.FieldTopic, field.TypeString, value)
	}
	if value, ok := ou.mutation.Data(); ok {
		_spec.SetField(outbox.FieldData, field.TypeBytes, value)
	}
	if value, ok := ou.mutation.InsertedAt(); ok {
		_spec.SetField(outbox.FieldInsertedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OutboxUpdateOne is the builder for updating a single Outbox entity.
type OutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxMutation
}

// SetTopic sets the "topic" field.
func (ouo *OutboxUpdateOne) SetTopic(s string) *OutboxUpdateOne {
	ouo.mutation.SetTopic(s)
	return ouo
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (ouo *OutboxUpdateOne) SetNillableTopic(s *string) *OutboxUpdateOne {
	if s != nil {
		ouo.SetTopic(*s)
	}
	return ouo
}

// SetData sets the "data" field.
func (ouo *OutboxUpdateOne) SetData(b []byte) *OutboxUpdateOne {
	ouo.mutation.SetData(b)
	return ouo
}

// SetInsertedAt sets the "inserted_at" field.
func (ouo *OutboxUpdateOne) SetInsertedAt(t time.Time) *OutboxUpdateOne {
	ouo.mutation.SetInsertedAt(t)
	return ouo
}

// SetNillableInsertedAt sets the "inserted_at" field if the given value is not nil.
func (ouo *OutboxUpdateOne) SetNillableInsertedAt(t *time.Time) *OutboxUpdateOne {
	if t != nil {
		ouo.SetInsertedAt(*t)
	}
	return ouo
}

// Mutation returns the OutboxMutation object of the builder.
func (ouo *OutboxUpdateOne) Mutation() *OutboxMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OutboxUpdate builder.
func (ouo *OutboxUpdateOne) Where(ps ...predicate.Outbox) *OutboxUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OutboxUpdateOne) Select(field string, fields ...string) *OutboxUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Outbox entity.
func (ouo *OutboxUpdateOne) Save(ctx context.Context) (*Outbox, error) {
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OutboxUpdateOne) SaveX(ctx context.Context) *Outbox {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OutboxUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ouo *OutboxUpdateOne) sqlSave(ctx context.Context) (_node *Outbox, err error) {
	_spec := sqlgraph.NewUpdateSpec(outbox.Table, outbox.Columns, sqlgraph.NewFieldSpec(outbox.FieldID, field.TypeInt64))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Outbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outbox.FieldID)
		for _, f := range fields {
			if !outbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.Topic(); ok {
		_spec.SetField(outbox.FieldTopic, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Data(); ok {
		_spec.SetField(outbox.FieldData, field.TypeBytes, value)
	}
	if value, ok := ouo.mutation.InsertedAt(); ok {
		_spec.SetField(outbox.FieldInsertedAt, field.TypeTime, value)
	}
	_node = &Outbox{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
