// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Mail is the predicate function for mail builders.
type Mail func(*sql.Selector)

// Outbox is the predicate function for outbox builders.
type Outbox func(*sql.Selector)
