// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"encore.app/receiver/ent/incomingmail"
	"encore.app/receiver/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IncomingMailDelete is the builder for deleting a IncomingMail entity.
type IncomingMailDelete struct {
	config
	hooks    []Hook
	mutation *IncomingMailMutation
}

// Where appends a list predicates to the IncomingMailDelete builder.
func (imd *IncomingMailDelete) Where(ps ...predicate.IncomingMail) *IncomingMailDelete {
	imd.mutation.Where(ps...)
	return imd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (imd *IncomingMailDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, imd.sqlExec, imd.mutation, imd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (imd *IncomingMailDelete) ExecX(ctx context.Context) int {
	n, err := imd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (imd *IncomingMailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(incomingmail.Table, sqlgraph.NewFieldSpec(incomingmail.FieldID, field.TypeInt))
	if ps := imd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, imd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	imd.mutation.done = true
	return affected, err
}

// IncomingMailDeleteOne is the builder for deleting a single IncomingMail entity.
type IncomingMailDeleteOne struct {
	imd *IncomingMailDelete
}

// Where appends a list predicates to the IncomingMailDelete builder.
func (imdo *IncomingMailDeleteOne) Where(ps ...predicate.IncomingMail) *IncomingMailDeleteOne {
	imdo.imd.mutation.Where(ps...)
	return imdo
}

// Exec executes the deletion query.
func (imdo *IncomingMailDeleteOne) Exec(ctx context.Context) error {
	n, err := imdo.imd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{incomingmail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (imdo *IncomingMailDeleteOne) ExecX(ctx context.Context) {
	if err := imdo.Exec(ctx); err != nil {
		panic(err)
	}
}
