// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"encore.app/receiver/ent/incomingmail"
	"encore.app/receiver/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IncomingMailQuery is the builder for querying IncomingMail entities.
type IncomingMailQuery struct {
	config
	ctx        *QueryContext
	order      []incomingmail.OrderOption
	inters     []Interceptor
	predicates []predicate.IncomingMail
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IncomingMailQuery builder.
func (imq *IncomingMailQuery) Where(ps ...predicate.IncomingMail) *IncomingMailQuery {
	imq.predicates = append(imq.predicates, ps...)
	return imq
}

// Limit the number of records to be returned by this query.
func (imq *IncomingMailQuery) Limit(limit int) *IncomingMailQuery {
	imq.ctx.Limit = &limit
	return imq
}

// Offset to start from.
func (imq *IncomingMailQuery) Offset(offset int) *IncomingMailQuery {
	imq.ctx.Offset = &offset
	return imq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (imq *IncomingMailQuery) Unique(unique bool) *IncomingMailQuery {
	imq.ctx.Unique = &unique
	return imq
}

// Order specifies how the records should be ordered.
func (imq *IncomingMailQuery) Order(o ...incomingmail.OrderOption) *IncomingMailQuery {
	imq.order = append(imq.order, o...)
	return imq
}

// First returns the first IncomingMail entity from the query.
// Returns a *NotFoundError when no IncomingMail was found.
func (imq *IncomingMailQuery) First(ctx context.Context) (*IncomingMail, error) {
	nodes, err := imq.Limit(1).All(setContextOp(ctx, imq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{incomingmail.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (imq *IncomingMailQuery) FirstX(ctx context.Context) *IncomingMail {
	node, err := imq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IncomingMail ID from the query.
// Returns a *NotFoundError when no IncomingMail ID was found.
func (imq *IncomingMailQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = imq.Limit(1).IDs(setContextOp(ctx, imq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{incomingmail.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (imq *IncomingMailQuery) FirstIDX(ctx context.Context) int {
	id, err := imq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IncomingMail entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IncomingMail entity is found.
// Returns a *NotFoundError when no IncomingMail entities are found.
func (imq *IncomingMailQuery) Only(ctx context.Context) (*IncomingMail, error) {
	nodes, err := imq.Limit(2).All(setContextOp(ctx, imq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{incomingmail.Label}
	default:
		return nil, &NotSingularError{incomingmail.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (imq *IncomingMailQuery) OnlyX(ctx context.Context) *IncomingMail {
	node, err := imq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IncomingMail ID in the query.
// Returns a *NotSingularError when more than one IncomingMail ID is found.
// Returns a *NotFoundError when no entities are found.
func (imq *IncomingMailQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = imq.Limit(2).IDs(setContextOp(ctx, imq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{incomingmail.Label}
	default:
		err = &NotSingularError{incomingmail.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (imq *IncomingMailQuery) OnlyIDX(ctx context.Context) int {
	id, err := imq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IncomingMails.
func (imq *IncomingMailQuery) All(ctx context.Context) ([]*IncomingMail, error) {
	ctx = setContextOp(ctx, imq.ctx, "All")
	if err := imq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IncomingMail, *IncomingMailQuery]()
	return withInterceptors[[]*IncomingMail](ctx, imq, qr, imq.inters)
}

// AllX is like All, but panics if an error occurs.
func (imq *IncomingMailQuery) AllX(ctx context.Context) []*IncomingMail {
	nodes, err := imq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IncomingMail IDs.
func (imq *IncomingMailQuery) IDs(ctx context.Context) (ids []int, err error) {
	if imq.ctx.Unique == nil && imq.path != nil {
		imq.Unique(true)
	}
	ctx = setContextOp(ctx, imq.ctx, "IDs")
	if err = imq.Select(incomingmail.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (imq *IncomingMailQuery) IDsX(ctx context.Context) []int {
	ids, err := imq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (imq *IncomingMailQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, imq.ctx, "Count")
	if err := imq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, imq, querierCount[*IncomingMailQuery](), imq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (imq *IncomingMailQuery) CountX(ctx context.Context) int {
	count, err := imq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (imq *IncomingMailQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, imq.ctx, "Exist")
	switch _, err := imq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (imq *IncomingMailQuery) ExistX(ctx context.Context) bool {
	exist, err := imq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IncomingMailQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (imq *IncomingMailQuery) Clone() *IncomingMailQuery {
	if imq == nil {
		return nil
	}
	return &IncomingMailQuery{
		config:     imq.config,
		ctx:        imq.ctx.Clone(),
		order:      append([]incomingmail.OrderOption{}, imq.order...),
		inters:     append([]Interceptor{}, imq.inters...),
		predicates: append([]predicate.IncomingMail{}, imq.predicates...),
		// clone intermediate query.
		sql:  imq.sql.Clone(),
		path: imq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		To string `json:"to,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IncomingMail.Query().
//		GroupBy(incomingmail.FieldTo).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (imq *IncomingMailQuery) GroupBy(field string, fields ...string) *IncomingMailGroupBy {
	imq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IncomingMailGroupBy{build: imq}
	grbuild.flds = &imq.ctx.Fields
	grbuild.label = incomingmail.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		To string `json:"to,omitempty"`
//	}
//
//	client.IncomingMail.Query().
//		Select(incomingmail.FieldTo).
//		Scan(ctx, &v)
func (imq *IncomingMailQuery) Select(fields ...string) *IncomingMailSelect {
	imq.ctx.Fields = append(imq.ctx.Fields, fields...)
	sbuild := &IncomingMailSelect{IncomingMailQuery: imq}
	sbuild.label = incomingmail.Label
	sbuild.flds, sbuild.scan = &imq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IncomingMailSelect configured with the given aggregations.
func (imq *IncomingMailQuery) Aggregate(fns ...AggregateFunc) *IncomingMailSelect {
	return imq.Select().Aggregate(fns...)
}

func (imq *IncomingMailQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range imq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, imq); err != nil {
				return err
			}
		}
	}
	for _, f := range imq.ctx.Fields {
		if !incomingmail.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if imq.path != nil {
		prev, err := imq.path(ctx)
		if err != nil {
			return err
		}
		imq.sql = prev
	}
	return nil
}

func (imq *IncomingMailQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IncomingMail, error) {
	var (
		nodes = []*IncomingMail{}
		_spec = imq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IncomingMail).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IncomingMail{config: imq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, imq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (imq *IncomingMailQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := imq.querySpec()
	_spec.Node.Columns = imq.ctx.Fields
	if len(imq.ctx.Fields) > 0 {
		_spec.Unique = imq.ctx.Unique != nil && *imq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, imq.driver, _spec)
}

func (imq *IncomingMailQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(incomingmail.Table, incomingmail.Columns, sqlgraph.NewFieldSpec(incomingmail.FieldID, field.TypeInt))
	_spec.From = imq.sql
	if unique := imq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if imq.path != nil {
		_spec.Unique = true
	}
	if fields := imq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incomingmail.FieldID)
		for i := range fields {
			if fields[i] != incomingmail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := imq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := imq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := imq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := imq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (imq *IncomingMailQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(imq.driver.Dialect())
	t1 := builder.Table(incomingmail.Table)
	columns := imq.ctx.Fields
	if len(columns) == 0 {
		columns = incomingmail.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if imq.sql != nil {
		selector = imq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if imq.ctx.Unique != nil && *imq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range imq.predicates {
		p(selector)
	}
	for _, p := range imq.order {
		p(selector)
	}
	if offset := imq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := imq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IncomingMailGroupBy is the group-by builder for IncomingMail entities.
type IncomingMailGroupBy struct {
	selector
	build *IncomingMailQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (imgb *IncomingMailGroupBy) Aggregate(fns ...AggregateFunc) *IncomingMailGroupBy {
	imgb.fns = append(imgb.fns, fns...)
	return imgb
}

// Scan applies the selector query and scans the result into the given value.
func (imgb *IncomingMailGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, imgb.build.ctx, "GroupBy")
	if err := imgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IncomingMailQuery, *IncomingMailGroupBy](ctx, imgb.build, imgb, imgb.build.inters, v)
}

func (imgb *IncomingMailGroupBy) sqlScan(ctx context.Context, root *IncomingMailQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(imgb.fns))
	for _, fn := range imgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*imgb.flds)+len(imgb.fns))
		for _, f := range *imgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*imgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := imgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IncomingMailSelect is the builder for selecting fields of IncomingMail entities.
type IncomingMailSelect struct {
	*IncomingMailQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ims *IncomingMailSelect) Aggregate(fns ...AggregateFunc) *IncomingMailSelect {
	ims.fns = append(ims.fns, fns...)
	return ims
}

// Scan applies the selector query and scans the result into the given value.
func (ims *IncomingMailSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ims.ctx, "Select")
	if err := ims.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IncomingMailQuery, *IncomingMailSelect](ctx, ims.IncomingMailQuery, ims, ims.inters, v)
}

func (ims *IncomingMailSelect) sqlScan(ctx context.Context, root *IncomingMailQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ims.fns))
	for _, fn := range ims.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ims.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ims.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
